# Generated by Django 3.2.6 on 2021-08-27 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AddField(
            model_name='customer',
            name='balance',
            field=models.IntegerField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='one_time_pickup',
            field=models.DateField(blank=True, default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='suspend_end',
            field=models.DateField(blank=True, default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='suspend_start',
            field=models.DateField(blank=True, default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='weekly_pickup_day',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='zip_code',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
