# Generated by Django 3.2.6 on 2021-08-30 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_auto_20210830_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='balance',
            field=models.IntegerField(blank=True, default=0, max_length=50, null=True),
        ),
    ]
